name: Java CI

on: 
   push:
      branches: 
      - "**"
   pull_request:
      branches:
      - "**"

jobs:
   build:
      name: Build
      runs-on: ubuntu-latest
      
      steps:
         - uses: actions/checkout@v2
           with:
              fetch-depth: 0
         - name: Set up JDK 11
           uses: actions/setup-java@v2
           with:
             java-version: '11'
             distribution: 'adopt'
         - name: Cache SonarCloud packages
           uses: actions/cache@v1
           with:
             path: ~/.sonar/cache
             key: ${{ runner.os }}-sonar
             restore-keys: ${{ runner.os }}-sonar
         - name: Cache Maven packages
           uses: actions/cache@v2
           with:
             path: ~/.m2
             key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml', '**/*.yml') }}
             restore-keys: ${{ runner.os }}-m2   
         - name: Build with Maven
           env:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
           run: mvn --batch-mode --update-snapshots verify -Pe2e-tests sonar:sonar -Dsonar.projectKey=Predictabowl_TempRepository01